<?php

$bands = array(
        "Handsome Ghost",
        "Explosions in the Sky",
        "Hammock",
        "Coldplay",
        "OneRepublic",
        "The Fray",
        "The 1975",
        "Small Black",
        "Lorde",
        "Andrew Belle",
        "Bastille",
        "Daughter",
        "Helios",
        "Imagine Dragons",
        "M83",
        "ODESZA",
        "Sia",
        "Bon Iver",
        "Made in Heights",
        "The Naked and Famous",
        "Sigur Rós",
        "Lemaitre",
        "Passion Pit",
        "MisterWives",
        "Smallpools",
        "AURORA",
        "Andrew McMahon",
        "Phoenix",
        "Florence + The Machine",
        "Day Wave",
        "The Chainsmokers",
        "Troye Sivan",
        "Carly Rae Jepsen",
        "twenty one pilots",
        "Melanie Martinez",
        "Jai Wolf",
        "Brothertiger",
        "Borns",
        "Kiiara",
        "LANY",
        "CHVRCHES",
        "Halsey"
        );
natcasesort($bands);     

?>