<?php

$bands = array(
        "Handsome Ghost",
        "Explosions in the Sky",
        "Hammock",
        "Coldplay",
        "OneRepublic",
        "The Fray",
        "The 1975",
        "Small Black",
        "Lorde",
        "Night Terrors of 1927",
        "Kina Grannis",
        "Andrew Belle",
        "Bastille",
        "Daughter",
        "Helios",
        "Imagine Dragons",
        "M83",
        "Odesza",
        "Sia",
        "Benjamin Francis Leftwich",
        "Bon Iver",
        "Hillsong United",
        "Switchfoot",
        "Made in Heights",
        "Of Monsters and Men",
        "Mumford & Sons",
        "The Naked and Famous",
        "Sigur Rós",
        "Lemaitre",
        "Passion Pit",
        "MisterWives",
        "Smallpools",
        "AURORA",
        "Andrew McMahon",
        "The Album Leaf",
        "Foster the People",
        "Cold War Kids",
        "Keith Kenniff",
        "Phoenix",
        "Florence + The Machine",
        "Birdy",
        "Owl City",
        "Day Wave",
        "The Chainsmokers",
        "Troye Sivan",
        "Carly Rae Jepsen",
        "twenty one pilots",
        "Melanie Martinez",
        "Jai Wolf",
        "Brothertiger"
        );
natcasesort($bands);     

?>